name: Restarter
main: com.minesnap.restarter.RestarterPlugin
version: "${project.version}"
author: AgentME (agentme49@gmail.com)
commands:
  rsquery:
    description: Queries how long until the next scheduled restart.
    usage: "Usage: /rsquery"
    permission: restarter.query
  rsset:
    description: Set the amount of time until the next restart.
    usage: "Usage: /rsset minutes"
    permission: restarter.set
permissions:
  restarter.*:
    description: Gives access to all Restarter commands
    children:
      restarter.query: true
      restarter.set: true
  restarter.query:
    description: Allows you to query how long until the next restart.
    default: op
  restarter.set:
    description: Allows you to set how long until the next restart.
    default: op
