name: Restarter
main: com.minesnap.restarter.RestarterPlugin
version: 0.1
author: AgentME (agentme49@gmail.com)
commands:
  rsquery:
    description: Queries how long until the next scheduled restart.
    usage: /rsquery
  rsset:
    description: Set the amount of time until the next restart.
    usage: "'/rsset [minutes]', for example, '/rsset 5'"
